<!DOCTYPE html>
<html>
<head>
    <title>All tools</title>

    <?php require "header.phtml" ?>

    <link rel="stylesheet" href="<?= $css_dir ?>homepage.css">
</head>
<body>
<div class="container text-center">
    <div class="tool-button">
        <button class="btn btn-outline-success btn-lg btn-block">Tool 1</button>
    </div>
    <div class="tool-button">
        <button class="btn btn-outline-success btn-lg btn-block">Tool 2</button>
    </div>
</div>
</body>
</html>
