<!DOCTYPE html>
<html>
<head>
    <title>All tools</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="<?= $css_dir ?>homepage.css">
</head>
<body>
<div class="container text-center">
    <div class="tool-button">
        <button class="btn btn-outline-success btn-lg btn-block">Tool 1</button>
    </div>
    <div class="tool-button">
        <button class="btn btn-outline-success btn-lg btn-block">Tool 2</button>
    </div>
</div>
</body>
</html>
